library(shinytest2)

test_that("{shinytest2} recording: trying time inputs reactions", {
  app <- AppDriver$new(name = "trying time inputs reactions", seed = 4177, height = 899, 
      width = 1379)
  app$expect_values(output = "fund_performance_plot")
  app$set_inputs(payment = "arrears")
  app$expect_values(output = "fund_performance_plot")
  app$set_inputs(duration_annuities = c(72, 97))
  app$expect_values(output = "number_premiums")
  app$set_inputs(number_premiums = 33)
  app$expect_values(output = "number_premiums")
  app$set_inputs(duration_annuities = c(54, 97))
  app$set_inputs(duration_annuities = c(45, 97))
  app$set_inputs(duration_annuities = c(38, 97))
  app$expect_values(output = "number_premiums")
  app$expect_values(output = "fund_performance_plot")
  app$set_inputs(guaranteed_rates_duration = 32)
  app$set_inputs(guaranteed_rates_duration = 41)
  app$set_inputs(duration_annuities = c(38, 68))
  app$expect_values(output = "fund_performance_plot")
  app$expect_values(output = "guaranteed_rates_duration")
  app$set_inputs(duration_annuities = c(74, 104))
  app$set_inputs(duration_annuities = c(74, 120))
  app$expect_values(output = "guaranteed_rates_duration")
  app$expect_values(output = "number_premiums")
  app$set_inputs(age = 52)
  app$expect_values(output = "duration_annuities")
  app$expect_values(output = "number_premiums")
  app$expect_values(output = "guaranteed_rates_duration")
})
